service: url-shortener

provider:
  name: aws
  runtime: nodejs22.x
  region: us-west-2 
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
      - dynamodb:PutItem
    Resource: arn:aws:dynamodb:us-west-2:956450360554:table/URLMappings

functions:
  createShortUrl:
    handler: lambdas/createShortUrl.handler
    events:
      - http:
          path: shorturl
          method: post
          cors: true

  redirectUrl:
    handler: lambdas/redirectUrl.handler
    events:
      - http:
          path: '{shortCode}'
          method: get
          cors: true
          
  getClickStats:
    handler: lambdas/getClickStats.handler
    events:
      - http:
          path: clickstats/{shortCode}
          method: get
          cors: true
  getDestinationUrl:
    handler: lambdas/getDestinationUrl.handler
    events:
      - http:
          path: lookup/{shortCode}
          method: get
          cors: true
