Resources:
  URLMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: URLMappings
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
        - AttributeName: originalUrl
          AttributeType: S
        - AttributeName: clicks
          AttributeType: N
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
