Resources:
  URLMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: URLMappings
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
        - AttributeName: originalUrl
          AttributeType: S
        - AttributeName: createdBy
          AttributeType: S 
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: originalUrl-index
          KeySchema:
            - AttributeName: originalUrl
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: createdBy-index
          KeySchema:
            - AttributeName: createdBy
              KeyType: HASH
          Projection:
            ProjectionType: ALL
