Resources:
  URLMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: URLMappings
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
